=== biurad/Console-lite/src/resources/clite.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "name": "Clite Package",
    "properties": {
        "application": {
            "description": "The application name, could be ConsoleLite or project name",
            "type": "string"
        },
        "generated": {
            "description": "Released date, in 'YYYY-MM-DD', 'YYYY-MM-DD HH:MM:SS' or 'YYYY-MM-DDTHH:MM:SSZ' format.",
            "type": "string"
        },
        "version": {
            "description": "The Phar build version number for updates",
            "type": "string"
        },
        "stuble": {
            "type": "object",
            "description": "The relative file path to the stub file, or the flag to use the default stub.",
            "additionalProperties": true
        },
        "compile": {
            "type": "object",
            "required": [ "config", "pack", "unpack" ],
            "description": "This is a package configuation for phar compile",
            "properties": {
                "config": {
                    "type": "object",
                    "description": "The phar build and unbuild configurations",
                    "additionalProperties": true
                },
                "pack": {
                    "type": "object",
                    "description": "The configurations to build a phar",
                    "additionalProperties": true
                },
                "unpack": {
                    "type": "object",
                    "description": "This configurations is to unpack files out of a phar file",
                    "additionalProperties": true
                }
            }
        }
    }
}

=== biurad/Console-lite/clite.json
{
    "application": "ConsoleLite Configuration",
    "generated": "2019/06/17 03:41",
    "version": "1.0.0",
    "stuble": {
        "config": {
            "name": "ConsoleLite Stub Generator"
        }
    },
    "compile": {
        "config": {
            "name": "clite.phar",
            "index": "docs/tests/test",
            "compression": 0,
            "signature": null
        },
        "pack": {
            "autoload": "vendor/autoload.php",
            "bin": "docs/tests/test",
            "files": [
                "clite.json",
                "composer.json"
            ],
            "directory": [
                "src/",
                "vendor/"
            ],
            "excludes": [
                "Tests/*",
                "!*.php"
            ]
        },
        "unpack": {
            "extract-to": "unpack",
            "files": null,
            "overwrite": true
        }
    }
}

=== biurad/Console-lite/docs/tests/fixtures/clite.json
{
    "application": "ConsoleLite Configuration",
    "generated": "2019/06/17 10:14",
    "version": "1.0.0",
    "stuble": {
        "config": {
            "name": "ConsoleLite Stub Generator"
        }
    },
    "compile": {
        "config": {
            "name": "app.phar",
            "index": "docs/tests/test",
            "compression": 0,
            "signature": null
        },
        "pack": {
            "autoload": "autoload.php",
            "bin": "docs/tests/test",
            "files": [
                "clite.json"
            ],
            "directory": [
                "src/",
                "vendor/"
            ],
            "excludes": [
                "Tests/*",
                "!*.php"
            ]
        },
        "unpack": {
            "extract-to": "unpack",
            "files": null,
            "overwrite": false
        }
    }
}
